# Generated by Django 6.0.1 on 2026-07-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="biography",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="band",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                ],
                default="HH",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "band",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="listings.band",
                    ),
                ),
            ],
        ),
    ]
