# Generated by Django 6.0.1 on 2026-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_band_biography_alter_band_genre_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="title",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
