# Generated by Django 6.0.1 on 2026-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_created_at_listing_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                ],
                default="HH",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="official_homepage",
            field=models.URLField(blank=True, null=True),
        ),
    ]
