# Generated by Django 6.0.1 on 2026-07-23 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_active_listing_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="year_formed",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2029),
                ]
            ),
        ),
    ]
