# Generated by Django 6.0.1 on 2026-07-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_band_year_formed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
