# Generated by Django 6.0.1 on 2026-07-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_listing_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
