# Generated by Django 6.0.1 on 2026-07-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_band_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="name",
            field=models.CharField(max_length=1000),
        ),
    ]
